sudo: required
services:
  - docker

before_install:
  - docker build -t jsaurabh95/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jsaurabh95/multi-docker npm test

after_success:
  - docker build -t jsaurabh95/multi-client ./client
  - docker build -t jsaurabh95/multi-nginx ./nginx
  - docker build -t jsaurabh95/multi-server ./server
  - docker build -t jsaurabh95/multi-worker ./worker

  - echo "$password" | docker login -u "$username" --password-stdin

  - docker push jsaurabh95/multi-client
  - docker push jsaurabh95/multi-nginx 
  - docker push jsaurabh95/multi-server
  - docker push jsaurabh95/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-fib"
  env: "DockerFib-env"
  bucket_name: "elasticbeanstalk-us-east-1-239175025842"
  bucket_path: "docker_multi"
  on:
    branch: master
  access_key_id:
    secure: "$key"
  secret_access_key:
    secure: "$secure_key"